services:
  - type: web
    name: codekiwi-app-backend
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APPSCRIPT_SECRET
        sync: false
